---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts
  - name: longhorn
    url: git+https://github.com/longhorn/longhorn.git@chart?ref=master
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
  - name: nginx
    url: https://kubernetes.github.io/ingress-nginx


helmDefaults:
  wait: true
  historyMax: 5

releases:
  # Bag repo for our local resources not provided by existing charts
  - name: means.no
    namespace: kube-system
    chart: ./means.no
    values:
      - cloudflare_key: 'ref+sops://secrets.enc.yaml#/cloudflare_key'
      - cloudflare_crt: 'ref+sops://secrets.enc.yaml#/cloudflare_crt'
  # Load balancer speaking bgp with our er-x.
  - name: metallb
    namespace: kube-system
    chart: bitnami/metallb
    values:
      - configInline:
          peers:
          - peer-address: 192.168.86.1
            peer-asn: 64512
            my-asn: 64512
          address-pools:
          - name: default
            protocol: bgp
            addresses:
            - 192.168.86.224/27
        speaker:
          secretValue: 'ref+sops://secrets.enc.yaml#/metallb_secret'
  - name: nginx
    chart: nginx/ingress-nginx
    namespace: kube-system
    values:
      - extraArgs:
          default-ssl-certificate: kube-system/means.no-tls
  # Longhorn block storage system
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn

  # Our base monitoring setup
  - name: prometheus
    namespace: monitoring
    chart: prometheus/prometheus
    values:
      - alertmanager:
          enabled: true
          persistentVolume:
            storageClass: longhorn
            size: 5Gi
          ingress:
            enabled: true
            hosts:
              - alerts.means.no

        pushgateway:
          enabled: false
        server:
          nodeSelector:
            kubernetes.io/hostname: mbox
          persistentVolume:
            storageClass: local-path
            size: 20Gi

  # Metrics server for internal monitoring.
  - name: metrics-server
    namespace: monitoring
    chart: bitnami/metrics-server
    values:
      - apiService:
          create: true

  # For dashboards, you know.
  - name: grafana
    chart: grafana/grafana
    namespace: monitoring
    values:
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://prometheus-server.monitoring.svc.cluster.local
                isDefault: true
      - dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards
      - dashboards:
          default:
            k8s:
              url: https://grafana.com/api/dashboards/6417/revisions/1/download
              datasource: Prometheus
      - adminPassword: 'ref+sops://secrets.enc.yaml#/grafana_password'
